-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('BUY', 'SELL', 'DIVIDEND', 'FUND_DISTRIBUTION', 'COMMISSION', 'TAX', 'CASH_DEPOSIT', 'CASH_WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT', 'BONUS_ISSUE', 'RIGHTS_ISSUE', 'SPLIT', 'OTHER');

