-- CreateEnum
CREATE TYPE "AlertType" AS ENUM ('ASSET_DAILY_RETURN', 'ASSET_AVG_DAILY_RETURN', 'PORTFOLIO_DAILY_LOSS', 'PORTFOLIO_DRAWDOWN', 'ASSET_WEIGHT', 'MONTHLY_REAL_RETURN_NEGATIVE', 'ASSET_PRICE', 'DATA_STALE');

